### ISSUE TITLE
anime episode don't show up on plex

### ISSUE THREAD

**Issue by mjeed02** [Cazzar/ShokoMetadata.bundle#50]
hi i'm new to shoko

but i did follow the setup tutorial
the shoko server still Importing anime from my hard drive
and the plex server doesn't show anything no series no episodes nothing
the Username and the Password and the Server IP and the Port are all correct
but nothing show up

i hope you could help me

**Comment by Cazzar** [comment]
If Shoko is still importing anime, ShokoMetadata will not show any episodes.

This is due to the way the file recognition works, is it defers to shoko asking "What is this file" instead of trying to guess from filename/path.

If it is not showing up the files that are recognised in Shoko (Shows up in the desktop) feel free to post the "Shoko Metadata Scanner.log" from the plex logs directory.

**Comment by mjeed02** [comment]
thank you but i fix it myself

the problem was i didn't change the python code in the scanners folder
although i did delete all database (now i know it wasn't necessary) i thought i needed to import all anime again

but thanks for the help
